### PR TITLE
a11y updates

### PR DESCRIPTION
**Pull request by scottaohara**
the following PR includes:
- markup updates to be more inline with expected document semantics  
- updated styles to retain previous styling with the new appropriate elements swapped in  
- no-js fallback to ensure content can be viewable without JavaScript  
- various instances of screen reader only content added, and updates to correct / remove some instances of content that was not being reported by ATs in a suitable manner.

see individual commits for more detail.

### CODE REVIEW

**Comment by kevincennis** [comment]
Thanks so much @scottaohara. This is great.

Since you're going down the road of `no-js` support, can you also change the `.load-transition` selector to be `html.js .load-transition` (or whatever you think is the appropriate way to do that)? Otherwise the body content will remain transparent for users with JS disabled.

👍 👍 👍

**Comment by scottaohara** [comment]
are you seeing something (or rather not) when JS is turned off?  

I already updated the selectors to:

``` css
.js .load-transition {} /* line 77 */
.js body.active .load-transition {} /* line 87 */
```

or are you referring to something outside of the CSS file that I missed?  

checking on FireFox/Chrome w/out JS, I'm seeing all the content?

**Comment by kevincennis** [comment]
Huh. I swear when I cloned it that wasn't there, but I do see it on the diff here. 

Clearly my bad.

**Comment by scottaohara** [comment]
np.

you have clearly seen some of my "oh, this was supposed to be in the last commit" commits.  so.  i aint throwin no stones, mang.

**Comment by kevincennis** [comment]
Okay, so just one other thing: looks like the font-size of "We use open-source software..." was notched down a bit. Should be 21px.

**Comment by scottaohara** [comment]
bamo

**Comment by kevincennis** [comment]
Awesome. Thanks so much Scott. 

Greatly appreciated.

**Pull request merged**
